---
contentdir: "content"
layoutdir: "layouts"
disqusShortname: "parasquid"
taxonomies:
  category: "categories"
baseurl: "http://life.beyondrails.com"
title: "Life Beyond Rails"
MetaDataFormat: "yaml"
permalinks:
  post: "/blog/:year/:month/:day/:title/"
theme: hyde-x
params:
  # Used when a given page doesn't set its own.
  defaultDescription: ""
  defaultKeywords: ""

  # Changes sidebar background and link/accent colours.
  # See below for more colour options.
  # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
  theme: "theme-base-0b"

  # Select a syntax highight.
  # Check the static/css/highlight directory for options.
  highlight: "sunburst"

  # Displays under the author name in the sidebar, keep it short.
  tagline: "Codesmithing by day. Airsculpting by night."

  # Metadata used to drive integrations.
  # googleAuthorship: "TristanGomez"
  googleAnalytics: "UA-41391404-1"
  gravatarHash: "e00d9254088a9db2e1875fc324402e2c"

  # Sidebar social links, avoid enabling too many of these if possible.
  # These should be full URLs.
  github: "https://github.com/parasquid"
  linkedin: "https://www.linkedin.com/in/parasquid"
  googleplus: "https://plus.google.com/u/1/+TristanGomez/posts"
  facebook: "https://www.facebook.com/parasquid"
  twitter: "https://twitter.com/parasquid"
---
